### ISSUE TITLE
Upload .rvt file ( PUT method)

### ISSUE THREAD

**Issue by violacambie** [radumg/DynaWeb#11] opened 2017-08-30 09:51 UTC
## Expected Behavior

I would want to upload a .rvt file on a bucket hosted online.

## Actual Behavior

 I'm using PUT method. I can add Headers and Parameters to the URL but I'm not sure how upload the Revit file.

## Steps to Reproduce the Problem

 The WebRequest.AddBody doesn't let me specify the type ( "binary") of the model: any suggestion?

## Specifications

    - Dynamo : 1.3

**Comment by violacambie** [comment] 2017-08-30 09:55
Hallo

I would want to upload a .rvt file on a bucket hosted online. 
I'm using PUT method. I can add Headers and Parameters to the URL but I'm not sure how upload the Revit file. 
The "WebRequest.AddBody" doesn't let me specify the type ( "binary") of the model: any suggestion?

- Dynamo : 1.3

**Comment by radumg** [comment] 2017-08-30 10:35
Hey @violacambie , thanks for writing this up!

As a first few suggestions :
- have you tried using the `WebRequest.AddFile` node ? It was designed for this and should be able to handle uploading the file for you.
- then, I would make the request a `POST` request, most web services accept creation of new records using that method.

![dynaweb add file](https://user-images.githubusercontent.com/11439624/29868456-e247a840-8d76-11e7-8886-128145077eee.PNG)

Also, could you let us know which service you're using, might help troubleshooting if we're able to look at their documentation and the DYN file.
I assume you're trying to upload to a bucket on either AWS S3 or Azure (blob storage) ?

**Comment by violacambie** [comment] 2017-08-30 14:08
Thanks for the replay!

yes I have tried the "WebRequest.AddFile" but I'm not sure the string should I use for a Revit model as "contentType": application/rvt? .rvt? application/octet-stream? binary?

Please have a look at the screenshot. With Postman I can simply upload a file as binary
![postman](https://user-images.githubusercontent.com/25077324/29876449-17985e74-8d9d-11e7-84fd-3301740745ab.JPG)

I'm uploading the models in a bucket on the Autodesk Platforme ( Forge ) and I'm not sure wich type of storage is.

**Comment by radumg** [comment] 2017-08-30 20:03
Hey Viola @violacambie ,
First off, thanks a lot for posting the `Postman` screenshot, helped a lot to know what works there and saved quite a few steps!

## Identify issue
 I signed up to a trial for Forge to test this out, was really curious how to get it working, here's what I found :
- `Content-Type` has to be `application/octet-stream`
- the `AddFile` node was failing because it's defaulting to uploading in a multi-part/form way. this is equivalent to switching `Postman` body to `form-data` instead of `binary`
- Forge doesn't accept `multi-part` data.
![forge multi-part](https://user-images.githubusercontent.com/11439624/29892375-43c4b992-8dc6-11e7-9771-e2af9c770654.PNG)

## Fix
So, I added another node to the package called `WebRequest.AddFileAsBytes` which adds the file as raw bytes to the request body.

![forge add file](https://user-images.githubusercontent.com/11439624/29892423-6a12df98-8dc6-11e7-8f33-45801bb867bd.png)

## Package updates
I'm releasing the updated, beta version of this on the Dynamo package manager tonight, search for `DynaWeb`.

## Sample
I've uploaded the entire DYN workflow in the samples folder, have a look at sample 7.

Please try it all out and let me know how you get on 🤓

**Comment by violacambie** [comment] 2017-08-31 10:05
Hey Radu@radumg

thanks for the updated version.
The _WebRequest.AddFileAsBytes_ works good! 

However the _WebRequest.SetMethod_ looks like is not working properly
![method](https://user-images.githubusercontent.com/25077324/29917848-842aa532-8e43-11e7-84c0-4f0dce8f6304.JPG)

I have solved this issues thanks your new _Execute.PUT_  !
![method v2](https://user-images.githubusercontent.com/25077324/29918044-3434a3ba-8e44-11e7-9ee5-7f7881e60091.JPG)

Plus the _Content-Type_ works both with _"application/octet-stream"_ and "application/x-www-form-urlencoded": should I prefer just one of those?

**Comment by radumg** [comment] 2017-08-31 13:10
Thanks for the feedback!

I had the same issue as your first screenshot - `SetMethod` is working, but the Request object is not being updated due to some Dynamo caching, which means it's still using the old token/request etc.
Disconnecting the nodes, closing the file and re-opening should do the trick - i'm looking into ways of forcing it to update each time.

Re: the `Content-Type`, if both work, then the `Forge` platform isn't enforcing/using that, so it should also work without :grin:

**Closed by radumg** 2017-08-31 13:10 UTC
Labels: awaiting feedback, use case
